# Generated by Django 6.1.1 on 2026-09-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('numero_socio', models.IntegerField(unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cuota_al_dia', models.BooleanField(default=True)),
            ],
        ),
    ]
